re-write ruby enumerable methods inside a module
chirchir12/enumerables pull request #1
Opened 2020-05-27 15:19 UTC by chirchir12

2020-05-28 17:38 UTC, nikasulo requested changes
# Great work! @chirchir12 
Please ensure you have a descriptive PR description before you request another review. This is a requirement before a review can be done

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-05-28 17:46 UTC, chirchir12 commented
# changes made 
*  The methods implemented include: #my_each, #my_each_with_index, #my_select, # my_all, #my_any ,#my_none ,#my_count, #my_map, #my_inject, my_map and multiply_els.

2020-05-28 20:08 UTC, mosesogwo requested changes
**Hi @chirchir12, good start on this project:+1:. Here are the recommended changes:**

:point_right: **my_all?** should be able to take an optional argument... the argument could be a Class, a Regex or any other pattern (a single character, word, etc). You can check this [doc](https://ruby-doc.org/core-2.6.5/Enumerable.html#method-i-all-3F) for the behaviour of the method in these scenarios.

:point_right:  When no block is given to **my_any?**, it should return `true` **only** if there is at least one element that is a truthy.
- `[false, nil, false].my_any?` should return `false`

:point_right: Just like in the case of **my_all?** above, Both **my_any?** and **my_none?** should be able to take an optional argument, which could be a Class, Regex or any other pattern.

:point_right: When no block or  argument is given, **my_none?** should return true if none of the members is true.
- `[false, nil, false].my_none?` should return `true`

:point_right: **my_inject** currently throws an error when called with a block on a range.
 - `(1..5).my_inject(4) { |prod, n| prod * n }` - should return 480 and not an error.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-05-28 20:08 UTC, mosesogwo commented on README.md
> +In this project,I implemented a Custom Enumerable method. The methods implemented include: #my_each, #my_each_with_index, #my_select, # my_all, #my_any ,#my_none ,#my_count, #my_map, #my_inject, my_m
The first sentence will only be correct as:
In this project,I implemented a Custom Enumerable module. or
In this project,I implemented Custom Enumerable methods

2020-05-28 20:08 UTC, mosesogwo commented on myenumerables.rb
> +  end
You should have a single my_map method that can take an optional proc. You don't have to separate the methods.

2020-05-28 20:08 UTC, mosesogwo commented on myenumerables.rb
> +      to_enum
The logic here does not produce correct results. A more correct logic will be
```
Declare new array
If proc
  run my_each with proc.call
  return new array
elsif block_given?
  run my_each with yield
  return new_array
else
 to_enum
end
```

2020-05-29 10:27 UTC, rOluochKe requested changes
Hello Team!
### You have done really good and for also making changes from the previous reviews so far :clap: Just one more method to go.
- [ ] my_map is not passing the test case
![map](https://user-images.githubusercontent.com/8114528/83249896-f4679800-a1af-11ea-985b-5f2bd0ffb47e.png)
### Make the change and submit for another code review. good luck.
- Happy coding!

By Raymond
slack @iamraymond

2020-05-29 10:41 UTC, chirchir12 commented
### implemented changes as requested. Kindly check it on

2020-05-29 10:54 UTC, rOluochKe approved these changes
Hello Team!
### You have done well :clap: The project looks good, therefore, it has been approved. Congratulations :boom: :100:
### You can merge and submit a project completion form from the dashboard. Good luck with the next project. 
- Happy coding!

2020-05-29 10:58 UTC, merged